### PR TITLE
jwt: Fix Verify methods documentation

### LINKED ISSUE #71: Documentation for VerifyExpiresAt, VerifyNotBefore and VerifyIssuedAt is incorrect
Migrated from https://github.com/dgrijalva/jwt-go/issues/360:

>  nathan-fiscaletti commented on Sep 28, 2019
> 
> The VerifyExpiresAt function for Claims has incorrect or unclear documentation. It states that it will compare the exp claim to cmp, which is indicative of a == comparison, when in reality it does a cmp <= exp comparison.

### PR DESCRIPTION
**Pull request by lggomez**
Fixes #71

### CODE REVIEW

File: claims.go [hunk 1]
```diff
@@ -64,13 +64,13 @@ func (c *StandardClaims) VerifyAudience(cmp string, req bool) bool {
 }
 
 // VerifyExpiresAt compares the exp claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// If req is false, this method will return true if cmp <= exp or if exp is unset
```
[the remark this answers is not in the document]
Comment (lggomez) [reply claims.go]: That sounds better. Done

File: claims.go [hunk 2]
```diff
@@ -63,14 +63,14 @@ func (c *StandardClaims) VerifyAudience(cmp string, req bool) bool {
 	return verifyAud([]string{c.Audience}, cmp, req)
 }
 
-// VerifyExpiresAt compares the exp claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyExpiresAt compares the exp claim against cmp (cpp <= exp).
```
Comment (oxisto) [inline claims.go:66]:
```suggestion
// VerifyExpiresAt compares the exp claim against cmp (cmp <= exp).
```

File: claims.go [hunk 3]
```diff
@@ -63,14 +63,14 @@ func (c *StandardClaims) VerifyAudience(cmp string, req bool) bool {
...
+// If req is false, it will return true, if exp is unset.
 func (c *StandardClaims) VerifyExpiresAt(cmp int64, req bool) bool {
 	return verifyExp(c.ExpiresAt, cmp, req)
 }
 
-// VerifyIssuedAt compares the iat claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyIssuedAt compares the exp claim against cmp (cpp >= iat).
```
Comment (oxisto) [inline claims.go:72]:
```suggestion
// VerifyIssuedAt compares the iat claim against cmp (cmp >= iat).
```

File: claims.go [hunk 4]
```diff
@@ -81,8 +81,8 @@ func (c *StandardClaims) VerifyIssuer(cmp string, req bool) bool {
 	return verifyIss(c.Issuer, cmp, req)
 }
 
-// VerifyNotBefore compares the nbf claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyNotBefore compares the exp claim against cmp (cpp >= nbf).
```
Comment (oxisto) [inline claims.go:84]:
```suggestion
// VerifyNotBefore compares the nbf claim against cmp (cmp >= nbf).
```

File: map_claims.go [hunk 5]
```diff
@@ -31,8 +31,8 @@ func (m MapClaims) VerifyAudience(cmp string, req bool) bool {
 	return verifyAud(aud, cmp, req)
 }
 
-// VerifyExpiresAt compares the exp claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyExpiresAt compares the exp claim against cmp (cpp <= exp).
```
Comment (oxisto) [inline map_claims.go:34]:
```suggestion
// VerifyExpiresAt compares the exp claim against cmp (cmp <= exp).
```

File: map_claims.go [hunk 6]
```diff
@@ -48,8 +48,8 @@ func (m MapClaims) VerifyExpiresAt(cmp int64, req bool) bool {
 	return false
 }
 
-// VerifyIssuedAt compares the iat claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyIssuedAt compares the exp claim against cmp (cpp >= iat).
```
Comment (oxisto) [inline map_claims.go:51]:
```suggestion
// VerifyIssuedAt compares the iat claim against cmp (cmp >= iat).
```

File: map_claims.go [hunk 7]
```diff
@@ -72,8 +72,8 @@ func (m MapClaims) VerifyIssuer(cmp string, req bool) bool {
 	return verifyIss(iss, cmp, req)
 }
 
-// VerifyNotBefore compares the nbf claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyNotBefore compares the exp claim against cmp (cpp >= nbf).
```
Comment (oxisto) [inline map_claims.go:75]:
```suggestion
// VerifyNotBefore compares the nbf claim against cmp (cmp >= nbf).
```

File: claims.go [hunk 8]
```diff
@@ -81,8 +81,8 @@ func (c *StandardClaims) VerifyIssuer(cmp string, req bool) bool {
 	return verifyIss(c.Issuer, cmp, req)
 }
 
-// VerifyNotBefore compares the nbf claim against cmp.
-// If required is false, this method will return true if the value matches or is unset
+// VerifyNotBefore compares the exp claim against cmp (cmp >= nbf).
```
Comment (oxisto) [inline claims.go:84]:
```suggestion
// VerifyNotBefore compares the nbf claim against cmp (cmp >= nbf).
```

One more :) then we are good to go.

**Review by oxisto — DISMISSED** [review]

**Review by oxisto — APPROVED** [review]
